version: '3'

services:
  traefik:
    image: traefik:latest
    networks:
      - webgateway
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/traefik.toml:/traefik.toml
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.brewmap.co"

networks:
  webgateway:
    external:
      name: traefik-net
