version: '3'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=9000"
        - "traefik.docker.network=traefik-net"
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.brewmap.co"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:
    external:
      name: traefik-net
