version: 2

jobs:
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          working_directory: ~/project/docker_swarm
          command: terraform init
      - run:
          name: Apply Terraform config
          working_directory: ~/project/docker_swarm
          command: |
            terraform plan

workflows:
  version: 2
  plan_and_approve:
    jobs:
      - apply
