version: 2

jobs:
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          working_directory: ~/project/docker_swarm
          command: |
            terraform init \
              -backend-config="access_key=${AWS_ACCESS_KEY}" \
              -backend-config="secret_key=${AWS_SECRET_KEY}"

      - run:
          name: Apply Terraform config
          working_directory: ~/project/docker_swarm
          command: |
            terraform apply

workflows:
  version: 2
  plan_and_approve:
    jobs:
      - apply
