version: 2

jobs:
  build:
    docker:
      - image: timmyers/brewmap-infrastructure
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          working_directory: ~/project/docker_swarm
          command: |
            terraform init \
              -backend-config="access_key=${AWS_ACCESS_KEY}" \
              -backend-config="secret_key=${AWS_SECRET_KEY}"

      - run:
          name: Apply Terraform config
          working_directory: ~/project/docker_swarm
          command: |
            terraform apply

      - add_ssh_keys:
          fingerprints:
            - "90:86:b5:e2:22:96:a4:0c:3e:4e:56:c8:e5:06:55:a1"

      - run:
          name: Ansible Playbook
          working_directory: ~/project/docker_swarm
          command: |
            ansible-playbook --version
            ./generateAnsibleInventory.sh
            ansible-galaxy install atosatto.docker-swarm
            export ANSIBLE_FORCE_COLOR=true
            ansible-playbook \
              -i hosts.json \
              playbook.yml

  deploy-traefik:
    docker:
      - image: timmyers/brewmap-infrastructure
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          working_directory: ~/project/docker_swarm
          command: |
            terraform init \
              -backend-config="access_key=${AWS_ACCESS_KEY}" \
              -backend-config="secret_key=${AWS_SECRET_KEY}"
            ./generateAnsibleInventory.sh
      - run:
          name: Ansible Playbook
          working_directory: ~/project/docker_stacks/traefik
          command: |
            ansible-playbook --version
            export ANSIBLE_FORCE_COLOR=true
            ansible-playbook \
              -i hosts.json \
              playbook.yml
