version: 2.0

jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          working_directory: ~/project/terraform
          command: terraform init
      - run:
          working_directory: ~/project/terraform
          command: |
            mkdir /tmp/artifacts;
            terraform plan > /tmp/artifacts/tfplan
      - store_artifacts:
          path: /tmp/artifacts
