version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          working_directory: ~/project/terraform
          command: terraform init
      - run:
          working_directory: ~/project/terraform
          command: |
            mkdir /tmp/artifacts;
            terraform plan > /tmp/artifacts/tfplan
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  plan_and_approve:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
