version: 2.0

jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          working_directory: ~/project/terraform
          command: terraform plan
