version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          working_directory: ~/project/terraform
          command: terraform init
      - run:
          working_directory: ~/project/terraform
          command: |
            mkdir /tmp/artifacts;
            terraform plan > /tmp/artifacts/tfplan
      - store_artifacts:
          path: /tmp/artifacts
  docker:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Connect to brewmap swarm with docker cloud
          command: |
            docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client -u timmyers -p c3drU3zZiuFJl4 timmyers/brewmap

workflows:
  version: 2
  plan_and_approve:
    jobs:
      - build
      - docker
      - hold:
          type: approval
          requires:
            - build
