{
  "docker_swarm_manager": {
    "hosts": {
      "swarm-master-107.170.243.231": {
        "ansible_host": "107.170.243.231",
        "ansible_user": "root",
        "ansible_python_interpreter": "/usr/bin/python3"
      }
    }
  },
  "docker_swarm_worker": {
    "hosts": {}
  }
}
