# Run docker swarm role
- name: "Provision Docker Swarm Cluster"
  hosts: all
  vars:
    skip_docker_py: True
    skip_group: True
  roles:
    - { role: atosatto.docker-swarm }

- name: Docker stacks
  hosts: docker_swarm_manager[0]
  become: true
  roles:
    - dockerStacks

# - name: Start portainer stack
#   hosts: docker_swarm_manager[0]
#   become: true
#   tasks:
#     - name: Copy portainer stack definition
#       copy:
#         src: ./portainerStack.yml
#         dest: /tmp/portainerStack.yml
#
#     - name: Start portainer stack
#       shell: >
#         docker stack deploy \
#         --compose-file /tmp/portainerStack.yml \
#         portainer

# - name: Start traefik service
#   hosts: docker_swarm_manager[0]
#   become: true
#   tasks:
#     - name: Check if portainer service running
#       shell: >
#         docker service inspect portainer
#       register: portainer_service
#       ignore_errors: yes
#
#     - name: Portainer service running?
#       debug: msg="Running {{ portainer_service.rc }}"
#
#     - name: Add portainer docker service
#       when: portainer_service.rc != 0
#       shell: >
#         docker service create \
#         --name portainer \
#         --publish 9000:9000 \
#         --constraint 'node.role == manager' \
#         --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
#         portainer/portainer \
#         -H unix:///var/run/docker.sock
#
