version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - webgateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.port=9090"
        - "traefik.docker.network=traefik-net"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:prometheus.brewmap.co"
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml

configs:
  prometheus:
    file: ./prometheus.yml

networks:
  webgateway:
    external:
      name: traefik-net
