- name: Copy portainer stack definition
  copy:
    src: portainer/portainerStack.yml
    dest: /tmp/portainerStack.yml

- name: Start portainer stack
  shell: >
    docker stack deploy \
    --compose-file /tmp/portainerStack.yml \
    portainer
